// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBoOarG3kGNLc9htr1q9ntDRHYeqSiBVuA',
    appId: '1:1017757398152:web:7cd7ddad2a9f89985f5b3d',
    messagingSenderId: '1017757398152',
    projectId: 'doctur-9284c',
    authDomain: 'doctur-9284c.firebaseapp.com',
    storageBucket: 'doctur-9284c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOrCVACgFgp5eGu-n495lcqZKYpBzP0oE',
    appId: '1:1017757398152:android:c8832eb8461dfec05f5b3d',
    messagingSenderId: '1017757398152',
    projectId: 'doctur-9284c',
    storageBucket: 'doctur-9284c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATKWb9riS_eBZRbOUyCXjXV_MV_xeOWok',
    appId: '1:1017757398152:ios:4d1f58fe7c76922e5f5b3d',
    messagingSenderId: '1017757398152',
    projectId: 'doctur-9284c',
    storageBucket: 'doctur-9284c.appspot.com',
    iosClientId: '1017757398152-pgv3ejehkpogbrvrge89i5ssvlsahgok.apps.googleusercontent.com',
    iosBundleId: 'com.example.docTur',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyATKWb9riS_eBZRbOUyCXjXV_MV_xeOWok',
    appId: '1:1017757398152:ios:60f2732d89fbc8a25f5b3d',
    messagingSenderId: '1017757398152',
    projectId: 'doctur-9284c',
    storageBucket: 'doctur-9284c.appspot.com',
    iosClientId: '1017757398152-v1ruvv1203tko87h4v21u9pii6fc5i1t.apps.googleusercontent.com',
    iosBundleId: 'com.example.docTur.RunnerTests',
  );
}
